version: '2'

services:
  zoo1:
    image: my_ubuntu_kafka:1.0
    hostname: zoo1
    restart: always
    ports:
      - 2181:2181
    tty: true
    volumes:
      - ./volume/my_config:/my_config
      - ./volume/my_data/zoo1:/data/zookeeper
#    command: ["sh", "my_config/zookeeper_init.sh"]
    networks:
      app_subnet:
        ipv4_address: 172.16.1.2

  zoo2:
    image: my_ubuntu_kafka:1.0
    hostname: zoo2
    restart: always
    ports:
      - 2182:2181
    volumes:
      - ./volume/my_config:/my_config
      - ./volume/my_data/zoo2:/data/zookeeper
    tty: true
#    command: sh my_config/zookeeper_init.sh
#    depends_on:
#      - zoo1
    networks:
      app_subnet:
        ipv4_address: 172.16.1.3

  zoo3:
    image: my_ubuntu_kafka:1.0
    hostname: zoo3
    restart: always
    ports:
      - 2183:2181
    volumes:
      - ./volume/my_config:/my_config
      - ./volume/my_data/zoo3:/data/zookeeper
    tty: true
#    command: sh my_config/zookeeper_init.sh
#    depends_on:
#      - zoo2
    networks:
      app_subnet:
        ipv4_address: 172.16.1.4

  kafka1:
    image: my_ubuntu_kafka:1.0
    hostname: kafka1
    restart: always
    ports:
      - 9092:9092
    volumes:
      - ./volume/my_config:/my_config
      - ./volume/my_data/kafka1:/data/kafka
    tty: true
#    command: sh my_config/kafka_init.sh
#    depends_on:
#      - zoo3
    networks:
      app_subnet:
        ipv4_address: 172.16.1.5

  kafka2:
    image: my_ubuntu_kafka:1.0
    hostname: kafka2
    restart: always
    ports:
      - 9093:9092
    volumes:
      - ./volume/my_config:/my_config
      - ./volume/my_data/kafka2:/data/kafka
    tty: true
#    command: sh my_config/kafka_init.sh
#    depends_on:
#      - kafka1
    networks:
      app_subnet:
        ipv4_address: 172.16.1.6

  kafka3:
    image: my_ubuntu_kafka:1.0
    hostname: kafka3
    restart: always
    ports:
      - 9094:9092
    volumes:
      - ./volume/my_config:/my_config
      - ./volume/my_data/kafka3:/data/kafka
    tty: true
#    command: sh my_config/kafka_init.sh
#    depends_on:
#      - kafka2
    networks:
      app_subnet:
        ipv4_address: 172.16.1.7

networks:
  app_subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
          gateway: 172.16.1.1
